name: pyviz
channels:
  - ioam
  - pyviz
  - conda-forge
  - bokeh
  - defaults
dependencies:
  # 
  # Versions for viz packages pinned to ensure mutual compatibility
  # 
  - bokeh=0.12.14
  - holoviews=1.9.5
  - geoviews=1.4.3
  - datashader=0.6.5
  - param=1.5.1
  - paramnb=2.0.3
  - parambokeh=0.2.2
  # 
  # Direct dependencies for package installation
  # 
  - yaml
  - requests
  - nodejs
  # 
  # Direct dependencies of most or all the tutorials
  # 
  - python=3.6
  - ipython=5        # Pinned to avoid tab-completion issue in ipython=6
  - numpy=1.14       # Pinned to avoid warnings with numpy=1.14 and bokeh=1.12.14
  - notebook>=5.1    # Pinned to avoid rate limiting for large images with notebook=5.0
  - dask=0.15.4      # Pinned in case of future API changes
  - jupyter
  - pandas
  - xarray
  # 
  # Directly imported dependencies of certain specialized tutorials
  # 
  - cartopy          # Required for some GeoViews examples

  # 
  # Indirect dependencies of our direct dependencies
  # 
  - selenium         # Required for exporting Bokeh plots to PNG
  - phantomjs        # Required for exporting Bokeh plots to PNG
  - netcdf4          # Required for reading .nc files
  - fastparquet      # Required for reading Parquet files
  - python-snappy    # Required for reading snappy-compressed Parquet files
  - pytest>=3.2      # Required by? Pinned to avoid installation problems on Windows with 3.1?
  - ipywidgets>=6,<7 # Required for paramnb. Pinned to avoid widgets scrolling for hover text.
  - cffi             # Unstated dependency of fastparquet?
  - pip:
    - git+https://github.com/jupyterhub/nbserverproxy
    - holoext==0.0.3
