#!/bin/bash

# Install a jupyter notebook + juypterlab extensions 

jupyter serverextension enable --py nbserverproxy --sys-prefix
#jupyter labextension install jupyterlab_bokeh
#jupyter labextension install @pyviz/jupyterlab_holoviews
